In [1]:
import numpy as np

In [2]:
np.random.seed(0)

In [3]:
#Each of 3 matrices
matrices = []

for i in range(3):
    M = np.random.randint(-10, 11, size=(3,3))
    matrices.append(M)
    print(f"Matrix {i}:\n", M)

Matrix 0:
 [[  2   5 -10]
 [ -7  -7  -3]
 [ -1   9   8]]
Matrix 1:
 [[-6 -4  2]
 [-9 -4 -3]
 [ 4  7 -5]]
Matrix 2:
 [[ 3 -2 -1]
 [10  9  6]
 [ 9 -5  5]]


In [4]:
#The inverses computed with the package
inverses = []

for i, M in enumerate(matrices):
    try:
        M_inv = np.linalg.inv(M)
        inverses.append(M_inv)
        print(f"Inverse Matrix {i}:\n", M_inv)
    except np.linalg.LinAlgError:
        inverses.append(None)
        print(f"Matrix{i} has no inverse.")

Inverse Matrix 0:
 [[-0.03094984 -0.13874066 -0.09071505]
 [ 0.06296692  0.00640342  0.08110993]
 [-0.07470651 -0.02454642  0.02241195]]
Inverse Matrix 1:
 [[-0.36607143  0.05357143 -0.17857143]
 [ 0.50892857 -0.19642857  0.32142857]
 [ 0.41964286 -0.23214286  0.10714286]]
Inverse Matrix 2:
 [[ 0.21551724  0.04310345 -0.00862069]
 [ 0.01149425  0.06896552 -0.08045977]
 [-0.37643678 -0.00862069  0.13505747]]


In [5]:
#Compute the product of each matrix with its inverse to check that you obtain the identity matrix.
for i in range(len(matrices)):
    if inverses[i] is not None:
        product = matrices[i] @ inverses[i]
        identity_check = np.round(product, 10)
        print(f"Product of Matrix {i} and its Inverse:\n", identity_check.astype(int))
    else:
        print(f"Matrix {i} has no inverse, so no verification is possible.")

Product of Matrix 0 and its Inverse:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
Product of Matrix 1 and its Inverse:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
Product of Matrix 2 and its Inverse:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
